name: tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize, ready_for_review] }
  push: { branches: [main] }

jobs:
  unit-tests:
    uses: vapor/ci/.github/workflows/run-unit-tests.yml@main
    with:
      with_release_mode_testing: true
      with_coverage: false
      with_tsan: false
      with_api_check: false
      with_linting: true
      extra_flags: "--disable-experimental-prebuilts --explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"

  cloudformation-lint:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup and run CloudFormation lint
        uses: ScottBrenner/cfn-lint-action@ed184e91f5085a2932501da8314e899e5e0ef5be # v2.7.1
        with:
          command: cfn-lint -t ./deploy/penny-discord-bot-stack.yml
