name: tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize, ready_for_review] }
  push: { branches: [main] }

jobs:
  unit-tests:
    uses: vapor/ci/.github/workflows/run-unit-tests.yml@main
    with:
      with_release_mode_testing: true
      with_coverage: false
      with_tsan: false
      with_api_check: false
      with_linting: true
      extra_flags: "--disable-experimental-prebuilts"

  cloudformation-lint:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup and run CloudFormation lint
        uses: ScottBrenner/cfn-lint-action@9636da81fb2e0cef75725d8dda11b0148940b7ae # v2.6.0
        with:
          command: cfn-lint -t ./deploy/penny-discord-bot-stack.yml
